feat: cache GitHub GET requests
getsynth/synth pull request #256
Opened 2021-11-26 14:04 UTC by juniorbassani

Implement caching for the GitHub GET requests. I defined the cached field to be valid for seven days. Let me know if it should be valid for longer or shorter periods.

2021-12-14 17:47 UTC, WiredSound requested changes
Hey man, thanks again for this change, and apologies for the delay in getting your PRs reviewed. This looks like a sensible change - though having so many users that we hit GitHub's API rate limit sounds like a great problem to have :)

I would suggest changing the name of the field `expiration_date` to something a little more specific (it could be misinterpreted to mean that the configuration file itself expires!) - perhaps something like `delay_version_check_until`.

As it currently stands these changes will still mean at least one request is made every time a Synth command runs but this is being addressed in #254 so not a problem. As mentioned in the other PR, it might be worth having the `synth version` command specifically override the caching and check GitHub every time it is run though.

One final thing is I would suggest is reducing the duration down from a week to maybe a day or so - as mentioned GH rate limit isn't much of a problem currently and we're hoping to be releasing new versions fairly regularly so it's best if users know sooner rather than later.

Thanks again for contributing!

2021-12-14 22:48 UTC, juniorbassani commented
@WiredSound, thanks again for your comments, they will definetly improve the code. As you mentioned, I will probably leave the `synth version` command issue for the other PR, but I'll address it nonetheless. 

I will let you know when I'm done.

2021-12-15 23:46 UTC, juniorbassani commented
@WiredSound, I made the necessary changes. 

I just renamed `delay_version_check_until` to `version_check_delay` just because it's shorter, but let me know if you prefer the previous name.

2021-12-16 00:07 UTC, WiredSound commented
Hey @juniorbassani , thanks, all looks good to me! We can address the double request made when running `synth version` in the other PR I think. @brokad what do we reckon? Okay to merge?

2021-12-23 14:45 UTC, merged