docs: update example to use `date_time` type instead of `string`
getsynth/synth pull request #258
Opened 2021-11-27 07:42 UTC by sassela

Addresses https://github.com/getsynth/synth/issues/257

Before:
```bash
➜  synth generate try-synth/ --size 2 | jq
Error: Unable to open the namespace "try-synth/"

Caused by:
    0: at file try-synth/users.json
    1: Failed to parse collection
    2: unknown variant `date_time`, expected one of `pattern`, `faker`, `categorical`, `serialized`, `uuid`, `truncated`, `format` at line 29 column 1
```

After:
```bash
➜  synth generate try-synth/ --size 2 | jq
{
  "users": [
    {
      "email": "margarete@example.org",
      "id": 1,
      "joined_on": {
        "date": "2016-03-04"
      }
    },
    {
      "email": "brody@example.com",
      "id": 2,
      "joined_on": {
        "date": "2016-07-08"
      }
    }
  ]
}
```

2021-12-23 16:46 UTC, WiredSound requested changes
Hey @sassela , thank you for your PR and sorry for the delay in getting back to you! Made some tiny (more stylistic rather than practical) suggestions. Thanks again

2021-12-23 16:46 UTC, WiredSound commented on README.md
> +            "type": "object",
Might make more sense to just have this as `"joined_on": { "type": "date_time", ... }` - i.e. remove the nested object.

2021-12-23 16:46 UTC, WiredSound commented on README.md
> +      "joined_on": {
These two other changes could then be changed back!

2021-12-30 07:39 UTC, sassela commented
thanks @WiredSound ! Makes sense, I've applied your suggestion

2022-01-16 17:32 UTC, merged